### ISSUE TITLE
Landscape Indicator Line

### ISSUE THREAD

**Issue by Krystel** [ezescaruli/ESTabBarController#13]
Hi @ezescaruli 

Thanks for this control I just love it!
I recently had to switch one app to landscape mode and this (attached) happens with the separator line.
If you click again on any button/index, it will "reset" and work just fine.
Any ideas? 

Thank you!

![simulator screen shot may 6 2016 5 11 11 pm](https://cloud.githubusercontent.com/assets/5189251/15075780/d77bdb86-13ae-11e6-9373-db16fdcfb17d.png)

**Comment by ezescaruli** [comment]
Hi @Krystel! Good catch.

I found the reason of the issue. I'm using a leading constraint for the indicator which constant is adjusted when moving to an index:
https://github.com/ezescaruli/ESTabBarController/blob/master/Source/Controllers/ESTabBarController.m#L374

However, the constant doesn't get updated when rotating the device.

I think the best solution for this is having that leading constraint to always be equal to the selected button leading, rather than using its constant to move it.

I'll fix it in a next PR!

**Comment by ezescaruli** [comment]
@Krystel This is fixed in `master` now.

I'll push a new version soon, but you can use that branch for now in your Podfile to avoid having this issue.

**Comment by ezescaruli** [comment]
@Krystel I had referenced the wrong PR, now the right one is merged :)

Also, pushed a new version, so you should be able to see the fix in it.

**Comment by Krystel** [comment]
I just saw this @ezescaruli ! 
Updating as we speak..
Thank you :)
