### ISSUE TITLE
Storyboard ViewControllers?

### ISSUE THREAD

**Issue by moudallal** [ezescaruli/ESTabBarController#5]
Instead of the XiB files in your Example app, I tried to create the view controllers in Main.storyboard and connected them to the .h and .m files but, for some reason, when I click the tab bar buttons I can't get to those view controllers. Help please?

**Comment by ezescaruli** [comment]
Hi @MhTheDev,

Would you have an example of how you're instantiating and setting the controllers from your storyboard?

Thanks!

**Comment by moudallal** [comment]
Hey @ezescaruli thank for your reply! Here's the example: https://github.com/MhTheDev/ESTabBarControllerTest
Xcode is telling me that the screens are unreachable (ViewControllers in Main.storyboard) but I don't know what to do! If you run the app, the labels won't show. Help?

**Comment by ezescaruli** [comment]
Hi @MhTheDev,

The issue is that the view controllers are being instantiated this way:

```
[[SearchViewController alloc] init];
```

But that doesn't use the storyboard to create them. In your case, you should first give your view controllers a Storyboard ID using the Identity Inspector:

![image](https://cloud.githubusercontent.com/assets/5781314/10237456/fae847ea-68f4-11e5-9599-87eef0967bb2.png)

And them instantiate the view controller using that ID. For example:

```
SearchViewController *searchViewController = [[self storyboard] instantiateViewControllerWithIdentifier:@"Search"];
[tabBarController setViewController:searchViewController atIndex:0];
```

Try that and see how it goes.

Cheers,

Ezequiel

**Comment by moudallal** [comment]
Hey @ezescaruli ! Thank you for your help! It works just perfect! Just for the note, your TabBarController is awesome.

**Comment by moudallal** [comment]
But how about to add this in your README ? Or maybe everyone but me knows this?

**Comment by ezescaruli** [comment]
@MhTheDev I think it's a pretty standard way of instantiating a view controller, so let's not add it for now ;)

**Comment by moudallal** [comment]
@ezescaruli So yeah, just exactly what I thought of. Everybody knows it but me. Anyway thanks again.

**Comment by ezescaruli** [comment]
@MhTheDev That's not a problem, man! We are all learning here ;)

**Comment by moudallal** [comment]
@ezescaruli That's true, we're all learning! :)
